spring:
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://39.107.102.24:3306/shop?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.ytu.shop.domain #实体类的存放路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
     com.ytu.shop.mapper : debug

server:
  port: 443
  servlet:
    session:
      timeout: 3600s
  tomcat:
    uri-encoding: UTF-8
    basedir: target/tomcat
  erver:
    ssl:
      key-store: classpath:1655744_nichang.site.pfx
      key-store-password: NLAH0poe
      keyStoreType: PKCS12



